# Generated by Django 4.1.7 on 2023-03-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='joining_date',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_login_date',
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
